### ISSUE TITLE
Support for 1.16.x?

### ISSUE THREAD

**Issue by Kichura** [ChachyDev/lazy-language-loader#1]
This might be a bit weird to ask this type of question but...have you ever planned to backport this mod to 1.16.x or do you wish to keep it on 1.17.x?

(reason: wanted to backport this on my own but then didn't manage to get that far cuz i have less knowledge in java)

**Comment by ChachyDev** [comment]
Hmmm, I could backport it for 1.16.x however I cannot provide assurance that it will be fully maintained

**Comment by ChachyDev** [comment]
Check out https://github.com/ChachyDev/lazy-language-loader/releases/tag/0.2.1-1.16.x for a backport. I have tested and it seemed to work so I believe it should be ready to use

**Comment by Kichura** [comment]
Tried to re-compile it in JDK 8 and it doesn't seem to work. However JDK 16 seems to work fine so won't be too much of a problem, just thought of pointing this out as 1.16.5's base was made in JDK 8 instead.

![image](https://user-images.githubusercontent.com/68134602/132243891-aa815499-b34e-412e-98e8-c0112c69189b.png)

**Comment by ChachyDev** [comment]
Oh alright whoops I forgot to downgrade those things, I'll fix those now

**Comment by ChachyDev** [comment]
Should be fixed as of this tag! https://github.com/ChachyDev/lazy-language-loader/releases/tag/0.2.2-1.16.x

**Comment by Kichura** [comment]
> 
> 
> Should be fixed as of this tag! https://github.com/ChachyDev/lazy-language-loader/releases/tag/0.2.2-1.16.x

The update is working properly, Thanks for your help!
(Will definitely add this to my modpack)
