### ISSUE TITLE
Update Modrinth for 1.20

### ISSUE THREAD

**Issue by JanLukasGithub** [ChachyDev/lazy-language-loader#11]
I use the old version on 1.20 and everything works fine so it would be nice for Modrinth to reflect that or else some people might just think that the new version is missing or not yet finished.

Or maybe others did have issues? Then please answer with a description.

**Comment by brunohpaiva** [comment]
There is already a version for 1.20 on Modrinth, it was released one week ago
Link: https://modrinth.com/mod/lazy-language-loader/version/0.3.3

**Comment by ChachyDev** [comment]
> I use the old version on 1.20 and everything works fine so it would be nice for Modrinth to reflect that or else some people might just think that the new version is missing or not yet finished.
> 
> Or maybe others did have issues? Then please answer with a description.

I believe it should crash? Not sure how that's happened but as bruno said above 1.20 is out on Modrinth, let me know if you have any issues

**Comment by JanLukasGithub** [comment]
I'm confused, did I leave this below the wrong mod...(?) But yeah everything works so just ignore this, sorry for the inconvenience.
