### ISSUE TITLE
[Bug] Loading screen displays when using "excitedze" easter egg

### ISSUE THREAD

**Issue by ghost** [ChachyDev/lazy-language-loader#12]
### [Bug] Loading screen displays when using "excitedze" easter egg
**Disclaimer: This is an easter egg feature and is not very well-known, so I don't expect a fix. This is mostly for documentation purposes.** 
When typing in "excitedze" into the crafting recipe search, Minecraft changes the language to Pirate Speak as an easter egg. lazy-language-loader typically removes the loading screen when changing languages. However, using this easter egg still shows the loading screen. 
To replicate, simply open the recipe book in the inventory and type in "excitedze".

**Comment by ChachyDev** [comment]
Thanks for letting me now! Should be fixed and out with the coming of 1.20.5

**Comment by ghost** [comment]
Thanks for fixing!
