### ISSUE TITLE
[Fabric 1.21.1 Loader 0.16.7] Crash on LanguageButton. Incompatibility with LanguageReload v1.6.1

### ISSUE THREAD

**Issue by Fireflasher21** [ChachyDev/lazy-language-loader#13]
Hello there,

i dont know in which to post this, I im just creating in both an [Issue](https://github.com/Jerozgen/LanguageReload/issues/66#issue-2600362133), as this crash happens exclusively, when both mods are loaded.

The game crashes when i click on the `Language` Button in Optionscreen. [Crash-Log](https://mclo.gs/8PwJ7ap)

Setup:
- Fabric 1.21.1
- Loader 0.16.7
- lazy-language-reload [0.3.7](https://modrinth.com/mod/lazy-language-loader/version/0.3.7)
- Language Reload [1.6.1](https://modrinth.com/mod/language-reload/version/1.6.1+1.21)

**Comment by ChachyDev** [comment]
I can't seem to be able to get Language Reload loaded in dev to debug this, I'll try another time and i'll let you know

**Comment by ChachyDev** [comment]
Solved by language reload
