### ISSUE TITLE
Curseforge

### ISSUE THREAD

**Issue by Madis0** [ChachyDev/lazy-language-loader#2]
I suggest uploading the mod to Curseforge as well for more exposure and making it easier for modpacks to include this.

**Comment by ChachyDev** [comment]
https://www.curseforge.com/minecraft/mc-mods/lazy-language-loader 👍

**Comment by Madis0** [comment]
Heads up, you forgot to mark the file as Fabric.

**Comment by ChachyDev** [comment]
Oh thank you! 😄

**Comment by Madis0** [comment]
Title is good for exposure, but the Curseforge client actually needs you to mark it on the JAR file itself:

![image](https://user-images.githubusercontent.com/8611110/133137158-29292f94-2356-430b-8cca-4dbcf8d40e65.png)

**Comment by ChachyDev** [comment]
Ahhh I see, does this require me to re-create the project? I've never really used curseforge before

**Comment by ChachyDev** [comment]
Ahhh i've seen it, thank you so much!
