### ISSUE TITLE
The search language does not change after changing the interface language.

### ISSUE THREAD

**Issue by Felix14-v2** [ChachyDev/lazy-language-loader#3]
[[Demo]](https://youtu.be/wGbOIQKNq4E)
In fact, it is very convenient when you can search items in English after working with Minecraft commands, but at the same time see the names of items in your native language. I think it should be an optional feature, not just a bug.

**Comment by ChachyDev** [comment]
I see. I'll probably work on this later today so be watching :eyes:

**Comment by ChachyDev** [comment]
I can't seem to reproduce this behaviour 🤔  What version of the game are you on?

**Comment by Felix14-v2** [comment]
Minecraft 1.17.1, Fabric 0.11.6. This also happens without other mods.

**Comment by ChachyDev** [comment]
Could you provide full reproduction steps

**Comment by ChachyDev** [comment]
Nevermind! Planning on fixing this game bug right now

**Comment by ChachyDev** [comment]
Turns out the issue comes from the mod itself 🤔 Fixing now

**Comment by ChachyDev** [comment]
This should be fixed as of https://github.com/ChachyDev/lazy-language-loader/commit/029aafb5def8fa4d2f23b3d16801648c2381882f. Closing this issue as it should now be resolved if you would like to use the version of this mod with this patch upgrade to 0.2.2
