### ISSUE TITLE
[1.18] 0.2.4 is actually set as a 1.17.x mod

### ISSUE THREAD

**Issue by SplendidAlakey** [ChachyDev/lazy-language-loader#5]
**MC** 1.18
**Lazy language loader** 0.2.4
**Fabric** loader 0.12.8; API 0.41.3

When trying to use 0.2.4, the game won't start as it's tagged as a 1.17.x mod [here](https://github.com/ChachyDev/lazy-language-loader/blob/1.18.x/dev/src/main/resources/fabric.mod.json). Should be 1.18.x

Log: https://gist.github.com/Footage2-Amply-Pounce/a437c213ccbacef8bfd90ad9d35d3b4c

**Comment by ChachyDev** [comment]
oh goodness oops, i'll quickly fix this

**Comment by ChachyDev** [comment]
Fixed in the latest commit, https://github.com/ChachyDev/lazy-language-loader/commit/ea7918f46654efc914b2d3aae002298492fabd30.
